// <auto-generated />
namespace S2021A6QP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ArtistMediaItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArtistMediaItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202108110620271_ArtistMediaItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
